### ISSUE TITLE
Some, if not all, verbiage of ktlint report is pre/appended to the source file after being formatted

### ISSUE THREAD

**Issue by publicclassoverflow** [cestef/kotlin-formatter#10] opened 2022-02-24 01:10 UTC
Please check out the screenshots and let me know if you have any idea of what is happening. Thanks!

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/25951007/155437488-4ce9bad9-8265-498b-a34e-999cc1bd1481.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/25951007/155437523-93b18a3f-6337-4588-a91f-8fb0d083a6b0.png">

Running macOS Monterey, vscode 1.64.2, and ktlint 0.44.0

**Comment by cstefFlexin** [comment] 2022-02-24 12:48
Hey thank you so much for reporting ! I'll try to take a look at the issue asap, even though I think this could be related to ktlint directly.

**Comment by cestef** [comment] 2022-02-25 08:24
I am indeed able to reproduce this on my side, this seems to be related with ktlint 0.44, I'll try to fix this asap !

**Comment by cestef** [comment] 2022-02-25 08:41
Fixed by 421ef4cccc401aa6ea2967b45985b88bca9bac4e
I messed up with the file formatting in the commit but all I changed was adding this line:

```ts
res = res.replace(/[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]+ \[.+\] .*(?:\n|\r)/g, "");
```
This just removes all the debug logs things, this is kindof a messy solution, but it should work  ¯\\\_(ツ)\_/¯

**Closed** 2022-02-25 08:41 UTC
Labels: bug

**Comment by risetarnished** [comment] 2022-02-25 19:20
That was fast! Thanks for the quick fix. 
The fix does look quite a bit of hack and I think it might introduce other _flaws_. 
Try adding a comment in the ktlint output's format, ie. this one
`// 11:14:25.625 [main] DEBUG com.pinterest.ktlint.Main - Discovered reporter with "baseline" id.`
anywhere in your code and format it.
But I'd be surprised if anybody adds such a comment lmao.

**Comment by cestef** [comment] 2022-02-26 07:21
You're right, I may need to add ^ and $ to the regexp so this kind of problem is less likely to happen (even though I don't think anyone would ever do that)
